services:
  dev-db:
    image: postgres:latest
    container_name: dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_api_example
    ports:
      - '5432:5432'
    networks:
    - freecodecamp
  test-db:
    image: postgres:latest
    container_name: test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_api_example
    #n√£o deve ser a mesma porta do dev-db para evitar conflitos
    ports:
      - '5434:5432'
    networks:
    - freecodecamp
networks:
  freecodecamp:
    driver: bridge